# Generated by Django 3.1.3 on 2020-12-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('jo_id_jornada', models.DecimalField(decimal_places=0, max_digits=18, primary_key=True, serialize=False, unique=True, verbose_name='ID Jornada')),
                ('jo_descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripcion')),
                ('jo_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('jo_fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('jo_usuario_creacion', models.CharField(max_length=50, verbose_name='Usuario creacion')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'ordering': ['jo_id_jornada'],
            },
        ),
    ]
