# Generated by Django 3.1.3 on 2020-12-17 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('cu_id_curso', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Curso')),
                ('cu_nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('cu_descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('cu_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('cu_fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('cu_usuario_creacion', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Usuario creacion')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'ordering': ['cu_id_curso'],
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('jo_id_jornada', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Jornada')),
                ('jo_descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripcion')),
                ('jo_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('jo_fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('jo_usuario_creacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario creacion')),
            ],
            options={
                'verbose_name': 'Jornada',
                'verbose_name_plural': 'Jornadas',
                'db_table': 'jornada',
                'ordering': ['jo_id_jornada'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('gr_id_grado', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Grado')),
                ('gr_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('gr_descripcion', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion')),
                ('gr_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('gr_fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('gr_usuario_creacion', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Usuario creacion')),
                ('gr_id_jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jornada')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'db_table': 'grado',
                'ordering': ['gr_id_grado'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('ho_id_grado_curso', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ciclo', models.CharField(max_length=4, verbose_name='Ciclo')),
                ('ho_usuario_catedratico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Catedratico')),
                ('ho_hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('ho_hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('ho_no_periodo', models.IntegerField(verbose_name='No Periodo')),
                ('ho_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('ho_fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('ho_usuario_creacion', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Usuario creacion')),
                ('ho_id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('ho_id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grado')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
                'ordering': ['ho_id_grado_curso'],
                'unique_together': {('ho_ciclo', 'ho_id_grado', 'ho_id_curso')},
            },
        ),
    ]
