# Generated by Django 3.1.3 on 2020-12-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jornada',
            table='jornada',
        ),
    ]
