# Generated by Django 3.1.3 on 2020-12-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201212_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='jo_id_jornada',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID Jornada'),
        ),
    ]
