# Generated by Django 3.1.3 on 2020-12-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201212_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('gr_id_grado', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Grado')),
                ('gr_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('gr_descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('gr_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('gr_fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('gr_usuario_creacion', models.CharField(max_length=50, verbose_name='Usuario creacion')),
                ('gr_id_jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jornada')),
            ],
        ),
    ]
