# Generated by Django 3.1.3 on 2020-12-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201212_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jornada',
            name='jo_usuario_creacion',
        ),
    ]
