# Generated by Django 3.1.3 on 2020-12-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_jornada_jo_usuario_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='jo_usuario_creacion',
            field=models.CharField(default='', max_length=50, verbose_name='Usuario creacion'),
            preserve_default=False,
        ),
    ]
