# Generated by Django 3.1.3 on 2020-12-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jornada_jo_usuario_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='jo_usuario_creacion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Usuario creacion'),
        ),
    ]
