# Generated by Django 3.1.3 on 2020-12-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201212_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='gr_descripcion',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descripcion'),
        ),
    ]
