# Generated by Django 3.1.3 on 2020-12-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201212_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='gr_usuario_creacion',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Usuario creacion'),
        ),
    ]
