# Generated by Django 3.1.3 on 2020-12-13 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201212_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('ho_id_grado_curso', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ciclo', models.CharField(max_length=4, verbose_name='Ciclo')),
                ('ho_usuario_catedratico', models.CharField(blank=True, max_length=50, null=True, verbose_name='Catedratico')),
                ('ho_hora_inicio', models.TimeField(verbose_name='Hora inicio')),
                ('ho_hora_fin', models.TimeField(verbose_name='Hora fin')),
                ('ho_no_periodo', models.IntegerField(verbose_name='No Periodo')),
                ('ho_estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('ho_fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('ho_usuario_creacion', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Usuario creacion')),
                ('ho_id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.curso')),
                ('ho_id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grado')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
                'ordering': ['ho_id_grado_curso'],
            },
        ),
    ]
