# Generated by Django 3.1.3 on 2020-12-15 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_horario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('ho_ciclo', 'ho_id_grado', 'ho_id_curso')},
        ),
    ]
